global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: "win-exporter"
    static_configs:
      - targets:
          - 10.1.1.106:9182
  - job_name: "nvidia_gpu_exporter"
    static_configs:
      - targets:
          - 10.1.1.106:9835
  - job_name: "speedtest"
    metrics_path: /probe
    params:
      script: [speedtest]
    static_configs:
      - targets:
          - speedtest:9469
    scrape_interval: 1m
    scrape_timeout: 30s
  - job_name: "script_exporter"
    metrics_path: /metrics
    static_configs:
      - targets:
          - speedtest:9469
