{
 "title": "bentoml",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,5m,15m,1h,6h,12h,1d,1w,2w,1M"
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests to API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bentoml_service_request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Requests per-second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "rate(bentoml_service_request_total{instance=\"emprestimosim-recurring-service:5000\", endpoint=\"/api\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(score_histogram_bucket[1m])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(score_histogram_bucket[1m])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(score_histogram_bucket[1m])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(score_histogram_bucket[1m])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(\n        rate(\n            container_cpu_usage_seconds_total{name=\"emprestimosim-recurring-service\"}[5m]\n            )\n        ) by (name)\n        /\n    sum(\n        container_spec_cpu_quota{name=\"emprestimosim-recurring-service\"} \n        / \n        container_spec_cpu_period{name=\"emprestimosim-recurring-service\"}\n    ) by (name), \"service\", \"$1\", \"name\", \"(.*)\") * 100",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(bentoml_service_request_duration_seconds_bucket{endpoint=\"/api\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Model processing time",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_time_processing", "legendFormat": "{{pid}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_working_set_bytes{name=\"emprestimosim-recurring-service\"}, \"services\", \"$1\", \"name\", \"(.*)\")\n        /\nlabel_replace(container_spec_memory_limit_bytes{name=\"emprestimosim-recurring-service\"}, \"services\", \"$1\", \"name\", \"(.*)\") * 100 > 0 < +INF",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "score_histogram_bucket{le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}