{
 "title": "bentoml",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,5m,15m,1h,6h,12h,1d,1w,2w,1M"
   },
   {
    "name": "service",
    "label": "service",
    "query": "data-science-personal-lending-emprestimosim-recurring-service-4000"
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "HTTP response count",
   "type": "timeseries",
   "description": "on endpoint /api",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(http_response_code, endpoint) (increase(bentoml_service_request_total{endpoint=\"/api\"}[1m]))",
     "legendFormat": "{{http_response_code}}"
    }
   ]
  },
  {
   "title": "Requests per-second",
   "type": "timeseries",
   "description": "instance / http_response_code",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(rate(bentoml_service_request_total{endpoint=\"/api\"}[$__interval]), \"instance\", \"$1\", \"instance\", \"(.*):.*\") > 0",
     "legendFormat": "{{instance}} - {{http_response_code}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "by instance",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by(instance) (rate(container_cpu_usage_seconds_total{container_label_MESOS_TASK_ID=~\".*$service.*\"}[5m]))\n    /\n    sum by (instance) (container_spec_cpu_quota{container_label_MESOS_TASK_ID=~\".*$service.*\"} / container_spec_cpu_period{container_label_MESOS_TASK_ID=~\".*$service.*\"}),\n    \"instance\", \"$1\", \"instance\", \"(.*):.*\"\n)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Score Histogram",
   "type": "bargauge",
   "description": "buckets: 0.25, 0.5, 0.75, 1.0",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (score_histogram_bucket{le!=\"+Inf\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Model processing time",
   "type": "timeseries",
   "description": "Sum of time expended for all workers of an instance between payload transformation and score prediction ",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (model_time_processing), \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_working_set_bytes{container_label_MESOS_TASK_ID=~\".*$service.*\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\") \n/\nlabel_replace(container_spec_memory_limit_bytes{container_label_MESOS_TASK_ID=~\".*$service.*\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")* 100 > 0 < +INF",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(score_histogram_bucket[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(score_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(score_histogram_bucket[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(score_histogram_bucket[$__rate_interval])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(score_histogram_bucket[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(score_histogram_bucket[$__rate_interval])))",
     "legendFormat": "0.25"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(bentoml_service_request_duration_seconds_bucket[$__interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(bentoml_service_request_duration_seconds_bucket[5m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(bentoml_service_request_duration_seconds_bucket[5m])))",
     "legendFormat": "0.25"
    }
   ]
  }
 ]
}