{
 "title": "Dell G15 monitoring",
 "tags": [
  "infra",
  "prometheus",
  "windows"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(windows_os_info{}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(windows_cpu_time_total\t{instance=\"$node\"}) by (core))) - avg(sum by (mode)(rate(windows_cpu_time_total{mode='idle',instance=\"$node\"}[$__rate_interval])))) * 100) / count(count(windows_cpu_time_total{instance=\"$node\"}) by (core))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((windows_os_physical_memory_free_bytes{instance=\"$node\"} * 100) / windows_os_visible_memory_bytes{instance=\"$node\"}))"
    }
   ]
  },
  {
   "title": "Virtual Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((windows_os_virtual_memory_bytes{instance=\"$node\"} - windows_os_virtual_memory_free_bytes{instance=\"$node\"}) / (windows_os_virtual_memory_bytes{instance=\"$node\"} )) * 100)"
    }
   ]
  },
  {
   "title": "C: Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((windows_logical_disk_free_bytes{instance=\"$node\",volume=\"C:\"} * 100) / windows_logical_disk_size_bytes{instance=\"$node\",volume=\"C:\"}))"
    }
   ]
  },
  {
   "title": "D: Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((windows_logical_disk_free_bytes{instance=\"$node\",volume=\"D:\"} * 100) / windows_logical_disk_size_bytes{instance=\"$node\",volume=\"D:\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_os_time{instance=\"$node\"} - windows_system_system_up_time{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total installed physical memory",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_cs_physical_memory_bytes{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "C: disk size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_logical_disk_size_bytes{instance=\"$node\",volume=\"C:\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Operating System",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_info{instance=\"$node\"}",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Installed logical processors",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_os_virtual_memory_bytes{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "D: disk size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_logical_disk_size_bytes{instance=\"$node\",volume=\"D:\"})"
    }
   ]
  },
  {
   "title": "Time zone",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_timezone{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "description": "Number of user sessions for which the operating system is storing state information currently",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_users{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(windows_cpu_time_total{mode=\"privileged\",instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "privileged"
    },
    {
     "expr": "avg by (instance)(rate(windows_cpu_time_total{mode='user',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "avg by (instance)(rate(windows_cpu_time_total{mode='dpc',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "dpc"
    },
    {
     "expr": "sum by (instance)(rate(windows_cpu_time_total{mode=\"interrupt\",instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "interrupt"
    },
    {
     "expr": "avg by (mode)(rate(windows_cpu_time_total{mode='idle',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "windows_os_visible_memory_bytes{instance=\"$node\"}\n-\nwindows_memory_free_and_zero_page_list_bytes{instance=\"$node\"}\n- (\n    windows_memory_standby_cache_reserve_bytes{instance=\"$node\"}\n    +\n    windows_memory_standby_cache_core_bytes{instance=\"$node\"}\n    +\n    windows_memory_standby_cache_normal_priority_bytes{instance=\"$node\"}\n)",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "windows_memory_standby_cache_reserve_bytes{instance=\"$node\"}\n+\nwindows_memory_standby_cache_core_bytes{instance=\"$node\"}\n+\nwindows_memory_standby_cache_normal_priority_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Standby"
    },
    {
     "expr": "windows_memory_free_and_zero_page_list_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "windows_os_paging_limit_bytes{instance=\"$node\"} - windows_os_paging_free_bytes{instance=\"$node\"}",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all logical disks",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{instance=\"$node\"} * 100) / windows_logical_disk_size_bytes{instance=\"$node\"})",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_os_visible_memory_bytes{instance=\"$node\"}",
       "legendFormat": "Total - OS visible memory"
      },
      {
       "expr": "windows_memory_available_bytes{instance=\"$node\"}",
       "legendFormat": "Available - immediately available for allocation to a process or for system use"
      },
      {
       "expr": "windows_memory_standby_cache_reserve_bytes{instance=\"$node\"}\n+\nwindows_memory_standby_cache_core_bytes{instance=\"$node\"}\n+\nwindows_memory_standby_cache_normal_priority_bytes{instance=\"$node\"}",
       "legendFormat": "Standby - cached data and code that is not actively in use by processes, the system and the system cache"
      },
      {
       "expr": "windows_memory_free_and_zero_page_list_bytes{instance=\"$node\"}",
       "legendFormat": "Free + Zero - assigned to the free and zero page lists, does not contain cached data"
      },
      {
       "expr": "windows_memory_modified_page_list_bytes{instance=\"$node\"}",
       "legendFormat": "Modified - cached data and code that is not actively in use; needs to be written out before it will be available for allocation"
      }
     ]
    },
    {
     "title": "Pagins Files",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_os_paging_limit_bytes{instance=\"$node\"}",
       "legendFormat": "Paging files limit"
      },
      {
       "expr": "windows_os_paging_free_bytes{instance=\"$node\"}",
       "legendFormat": "Free paging size"
      }
     ]
    },
    {
     "title": "Standby Page List",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_standby_cache_core_bytes{instance=\"$node\"}",
       "legendFormat": "Standby core priority"
      },
      {
       "expr": "windows_memory_standby_cache_normal_priority_bytes{instance=\"$node\"}",
       "legendFormat": "Standby normal priority"
      },
      {
       "expr": "windows_memory_standby_cache_reserve_bytes{instance=\"$node\"}",
       "legendFormat": "Reserve standby cache page"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_committed_bytes{instance=\"$node\"}",
       "legendFormat": "Committed virtual memory"
      },
      {
       "expr": "windows_memory_commit_limit{instance=\"$node\"}",
       "legendFormat": "Virtual memory that can be committed without having to extend the paging files"
      }
     ]
    },
    {
     "title": "Paged/Non-Paged Pool",
     "type": "timeseries",
     "description": "The paged/non-paged pool is an area of the system virtual memory that is used for objects that can/cannot be written to disk when they are not being used.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_pool_nonpaged_bytes{instance=\"$node\"}",
       "legendFormat": "Non-paged pool - must remain in physical memory"
      },
      {
       "expr": "windows_memory_pool_paged_bytes{instance=\"$node\"}",
       "legendFormat": "Paged pool"
      },
      {
       "expr": "windows_memory_pool_paged_resident_bytes{instance=\"$node\"}",
       "legendFormat": "Resident portion of paged pool"
      }
     ]
    },
    {
     "title": "File System Cache",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_cache_bytes{instance=\"$node\"}",
       "legendFormat": "File system cache"
      },
      {
       "expr": "windows_memory_cache_bytes_peak{instance=\"$node\"}",
       "legendFormat": "Maximum value since boot"
      },
      {
       "expr": "windows_memory_system_cache_resident_bytes{instance=\"$node\"}",
       "legendFormat": "Resident portion of file system cache - active in physical memory"
      }
     ]
    },
    {
     "title": "Page Fault Rates",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_memory_page_faults_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Overall rate at which faulted pages are handled by the processor"
      },
      {
       "expr": "rate(windows_memory_transition_faults_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Resolved by recovering pages rate"
      },
      {
       "expr": "rate(windows_memory_transition_pages_repurposed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Transition cache pages reused rate"
      },
      {
       "expr": "rate(windows_memory_write_copies_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Satisfied by copying the page from elsewhere in physical memory"
      },
      {
       "expr": "rate(windows_memory_cache_faults_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Page not found in file system cache"
      },
      {
       "expr": "rate(windows_memory_demand_zero_faults_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Zeroed pages"
      }
     ]
    },
    {
     "title": "Swap page read/write",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_memory_swap_page_reads_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Disk page reads - a single read operation reading several pages is still only counted once"
      },
      {
       "expr": "rate(windows_memory_swap_pages_read_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Pages read across all page reads - i.e. counting all pages read even if they are read in a single operation"
      },
      {
       "expr": "rate(windows_memory_swap_page_writes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Disk page writes - a single write operation writing several pages is still only counted once"
      },
      {
       "expr": "rate(windows_memory_swap_pages_written_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Pages written across all page writes - i.e. counting all pages written even if they are written in a single operation"
      },
      {
       "expr": "rate(windows_memory_swap_page_operations_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Total rate of swap page read and writes"
      }
     ]
    },
    {
     "title": "Pageable OS system code + device drivers",
     "type": "timeseries",
     "description": "These values do not include pages that must remain in physical memory and cannot be written to disk",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_system_code_resident_bytes{instance=\"$node\"}",
       "legendFormat": "Operating system code - resident"
      },
      {
       "expr": "windows_memory_system_code_total_bytes{instance=\"$node\"}",
       "legendFormat": "Operating system code - total"
      },
      {
       "expr": "windows_memory_system_driver_resident_bytes{instance=\"$node\"}",
       "legendFormat": "Device drivers - resident"
      },
      {
       "expr": "windows_memory_system_driver_total_bytes{instance=\"$node\"}",
       "legendFormat": "Device drivers - total"
      }
     ]
    },
    {
     "title": "Paged/Non-Paged Pool - Allocation Calls",
     "type": "timeseries",
     "description": "Number of calls to allocate space in the paged/non-paged pool, regardless of the amount of space allocated in each call",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_memory_pool_nonpaged_allocs_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Calls to allocate space in the non-paged pool"
      },
      {
       "expr": "rate(windows_memory_pool_paged_allocs_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Calls to allocate space in the paged pool"
      }
     ]
    }
   ]
  },
  {
   "title": "System Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_system_context_switches_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "sum(rate(windows_cpu_interrupts_total{instance=\"$node\"}[$__rate_interval]))",
       "legendFormat": "Hardware interrupts"
      }
     ]
    },
    {
     "title": "Interrupts Detail",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_cpu_interrupts_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Core {{core}}"
      }
     ]
    },
    {
     "title": "Clock Tick Interrupts",
     "type": "timeseries",
     "description": "Total number of received and serviced clock tick interrupts",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_cpu_clock_interrupts_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Core {{core}}"
      }
     ]
    },
    {
     "title": "Idle breaks",
     "type": "timeseries",
     "description": "Total number of time processor was woken from idle\t",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_cpu_idle_break_events_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Core {{core}}"
      }
     ]
    },
    {
     "title": "Received and serviced deferred procedure calls (DPCs)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_cpu_dpcs_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Core {{core}}"
      }
     ]
    },
    {
     "title": "Time spent in low-power idle states",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(state) (rate(windows_cpu_cstate_seconds_total{instance=\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Parking Status",
     "type": "timeseries",
     "description": "Parking Status represents whether a processor is parked or not",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_cpu_parking_status{instance=\"$node\"}",
       "legendFormat": "Core {{ core }}"
      }
     ]
    },
    {
     "title": "Core Frequency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "windows_cpu_core_frequency_mhz{instance=\"$node\"}*1000",
       "legendFormat": "Core {{ core }}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_system_exception_dispatches_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Total exceptions dispatched by the system"
      }
     ]
    },
    {
     "title": "Processor Queue",
     "type": "timeseries",
     "description": "Number of threads in the processor queue. There is a single queue for processor time even on computers with multiple processors.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_system_processor_queue_length{instance=\"$node\"}",
       "legendFormat": "Threads in the processor queue"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$node\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=\"$node\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "CPU time spent in user and system contexts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Time spent"
      }
     ]
    },
    {
     "title": "Processes & Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_os_processes{instance=\"$node\"}",
       "legendFormat": "Process contexts currently loaded or running"
      },
      {
       "expr": "windows_system_threads{instance=\"$node\"}",
       "legendFormat": "Number of Windows system threads"
      }
     ]
    },
    {
     "title": "System Calls",
     "type": "timeseries",
     "description": "Total combined calls to Windows NT system service routines by all processes running on the computer",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(windows_system_system_calls_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "System calls"
      }
     ]
    }
   ]
  },
  {
   "title": "System Timesync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Syncronized Drift",
     "type": "timeseries",
     "description": "Absolute time offset between the system clock and the chosen time source, in seconds.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "windows_time_computed_time_offset_seconds{instance=\"$node\"}",
       "legendFormat": "Absolute time offset between the system clock and the chosen time source, in seconds."
      },
      {
       "expr": "windows_time_ntp_round_trip_delay_seconds{instance=\"$node\"}",
       "legendFormat": "Total roundtrip delay experienced by the NTP client in receiving a response from the server for the most recent request, in seconds."
      }
     ]
    },
    {
     "title": "Time Adjustment",
     "type": "timeseries",
     "description": "Total adjustment made to the local system clock frequency by W32Time in parts per billion (PPB) units. 1 PPB adjustment implies the system clock was adjusted at a rate of 1 nanosecond per second (1 ns/s). The smallest possible adjustment can vary and is expected to be in the order of 100's of PPB.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_time_clock_frequency_adjustment_ppb_total{instance=\"$node\"}",
       "legendFormat": "Total adjustment made to the local system clock frequency by W32Time in parts per billion (PPB) units."
      }
     ]
    },
    {
     "title": "NTP Server Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_time_ntp_server_outgoing_responses_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Total number of requests responded to by the NTP server."
      },
      {
       "expr": "rate(windows_time_ntp_server_incoming_requests_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Total number of requests received by the NTP server."
      }
     ]
    },
    {
     "title": "Time Misc",
     "type": "timeseries",
     "description": "Active number of NTP Time sources being used by the client. This is a count of active, distinct IP addresses of time servers that are responding to this client's requests.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "windows_time_ntp_client_time_sources{instance=\"$node\"}",
       "legendFormat": "NTP Sources"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Free Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_logical_disk_free_bytes{instance=\"$node\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Volume Used Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_logical_disk_size_bytes{instance=\"$node\"}-windows_logical_disk_free_bytes{instance=\"$node\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_reads_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - read"
      },
      {
       "expr": "rate(windows_logical_disk_writes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - write"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_read_bytes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - read"
      },
      {
       "expr": "rate(windows_logical_disk_write_bytes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - write"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_read_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - read"
      },
      {
       "expr": "rate(windows_logical_disk_write_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - write"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "windows_logical_disk_avg_read_requests_queued{instance=\"$node\"}",
       "legendFormat": "{{volume}} - read"
      },
      {
       "expr": "windows_logical_disk_avg_write_requests_queued{instance=\"$node\"}",
       "legendFormat": "{{volume}} - write"
      },
      {
       "expr": "windows_logical_disk_requests_queued{instance=\"$node\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_read_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - read"
      },
      {
       "expr": "rate(windows_logical_disk_write_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}} - write"
      }
     ]
    },
    {
     "title": "Idle I/O",
     "type": "timeseries",
     "description": "Disk idle time (not servicing read/write requests)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_idle_seconds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "IO Splits",
     "type": "timeseries",
     "description": "Number of I/Os to the disk split into multiple I/Os",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_split_ios_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(windows_net_bytes_received_total{instance=\"$node\"}[$__rate_interval])*8",
       "legendFormat": "{{nic}} - Receive"
      },
      {
       "expr": "rate(windows_net_bytes_sent_total{instance=\"$node\"}[$__rate_interval])*8",
       "legendFormat": "{{nic}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic by Packets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(windows_net_packets_received_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Receive"
      },
      {
       "expr": "rate(windows_net_packets_sent_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(windows_net_packets_received_discarded_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Receive drop"
      },
      {
       "expr": "rate(windows_net_packets_outbound_discarded_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(windows_net_packets_received_errors_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Receive errors"
      },
      {
       "expr": "rate(windows_net_packets_outbound_errors_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_net_current_bandwidth_bytes{instance=\"$node\"}",
       "legendFormat": "{{ nic }} - Speed"
      }
     ]
    },
    {
     "title": "Unknown Packets Received",
     "type": "timeseries",
     "description": "Total packets received by interface that were discarded because of an unknown or unsupported protocol\t",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(windows_net_packets_received_unknown_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{nic}} - Receive Unknown"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_tcp_connections_established{instance=\"$node\"}",
       "legendFormat": "{{ af}} - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_segments_retransmitted_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{ af }} - segments retransmitted"
      }
     ]
    },
    {
     "title": "TCP IPv4",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_segments_received_total{instance=\"$node\",af=\"ipv4\"}[$__rate_interval])",
       "legendFormat": "Segments received, including those received in error"
      },
      {
       "expr": "rate(windows_tcp_segments_sent_total{instance=\"$node\",af=\"ipv4\"}[$__rate_interval])",
       "legendFormat": "Segments sent, including those on current connections, but excluding those containing only retransmitted bytes"
      },
      {
       "expr": "rate(windows_tcp_segments_retransmitted_total{instance=\"$node\",af=\"ipv4\"}[$__rate_interval])",
       "legendFormat": "Segments retransmitted"
      }
     ]
    },
    {
     "title": "TCP IPv6",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_segments_received_total{instance=\"$node\",af=\"ipv6\"}[$__rate_interval])",
       "legendFormat": "Segments received, including those received in error"
      },
      {
       "expr": "rate(windows_tcp_segments_sent_total{instance=\"$node\",af=\"ipv6\"}[$__rate_interval])",
       "legendFormat": "Segments sent, including those on current connections, but excluding those containing only retransmitted bytes"
      },
      {
       "expr": "rate(windows_tcp_segments_retransmitted_total{instance=\"$node\",af=\"ipv6\"}[$__rate_interval])",
       "legendFormat": "Segments retransmitted"
      }
     ]
    },
    {
     "title": "TCP Direct Transition IPv4",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_connections_active_total{instance=\"$node\",af=\"ipv4\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "rate(windows_tcp_connections_passive_total{instance=\"$node\",af=\"ipv4\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    },
    {
     "title": "TCP Direct Transition IPv6",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_connections_active_total{instance=\"$node\",af=\"ipv6\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "rate(windows_tcp_connections_passive_total{instance=\"$node\",af=\"ipv6\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    },
    {
     "title": "TCP Connection Failures",
     "type": "timeseries",
     "description": "TCP connections have made a direct transition to the CLOSED state from the SYN-SENT state or the SYN-RCVD state, plus the number of times TCP connections have made a direct transition from the SYN-RCVD state to the LISTEN state",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(windows_tcp_connection_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{ af }} - TCP connection failures"
      }
     ]
    }
   ]
  },
  {
   "title": "Windows Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter Scrape",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_exporter_collector_success{instance=\"$node\"}",
       "legendFormat": "{{collector}} - Scrape success"
      }
     ]
    },
    {
     "title": "Windows Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "windows_exporter_collector_duration_seconds{instance=\"$node\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Windows Exporter Perflib Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 264 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "windows_exporter_perflib_snapshot_duration_seconds{instance=\"$node\"}",
       "legendFormat": "perflib"
      }
     ]
    },
    {
     "title": "Windows Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 264 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_os_info{instance=\"$node\"}",
       "legendFormat": "{{product}}"
      }
     ]
    },
    {
     "title": "Windows Exporter Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 264 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_exporter_build_info{instance=\"$node\"}",
       "legendFormat": "{{product}}"
      }
     ]
    },
    {
     "title": "Windows Exporter Go Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 264 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_exporter_build_info{instance=\"$node\"}",
       "legendFormat": "{{product}}"
      }
     ]
    },
    {
     "type": "stat",
     "description": "FQDN",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 267 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_hostname{instance=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Hostname",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 269 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_hostname{instance=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}